/*
 * SonarQube
 * Copyright (C) 2009-2024 SonarSource SA
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package org.sonar.ce.task.projectanalysis.step;

import java.util.Date;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.sonar.api.utils.DateUtils;
import org.sonar.ce.task.projectanalysis.batch.BatchReportReader;
import org.sonar.ce.task.step.ComputationStep;
import org.sonar.core.util.CloseableIterator;
import org.sonar.scanner.protocol.output.ScannerReport.ContextProperty;
import org.sonar.db.DbClient;
import org.sonar.db.DbSession;
import org.sonar.ce.task.CeTask;

import static java.util.Collections.singleton;

/**
 * Add taskUuid generated by sonar to the cs_queue table.
 *
 * @see org.sonar.ce.task.step.ComputationStepExecutor
 */
public class CodescanJobLinkStep implements ComputationStep {

    private static final String CODESCAN_JOB_ID_SONAR_PARAM = "sonar.analysis.buildId";
    private static final Logger log = LoggerFactory.getLogger(CodescanJobLinkStep.class);

    private final BatchReportReader reportReader;
    private final DbClient dbClient;
    private final CeTask ceTask;

    public CodescanJobLinkStep(BatchReportReader reportReader, DbClient dbClient, CeTask ceTask) {
        this.reportReader = reportReader;
        this.dbClient = dbClient;
        this.ceTask = ceTask;
    }

    @Override
    public void execute(Context context) {
        log.info("Executing CodescanJobLinkStep {}", DateUtils.formatDate(new Date()));
        try (CloseableIterator<ContextProperty> it = reportReader.readContextProperties()) {
            it.forEachRemaining(
                    contextProperty -> {
                        String propertyKey = contextProperty.getKey();
                        if (propertyKey.equals(CODESCAN_JOB_ID_SONAR_PARAM)) {
                            log.info("In CodeScan Job ID Sonar Param");
                            try (DbSession dbSession = dbClient.openSession(false)) {
                                log.info("DB Client Open");
                                dbClient.csQueueDao().updateTaskUuid(
                                        dbSession, ceTask.getUuid(), contextProperty.getValue()
                                );
                                log.info("DB Client Before Commit");
                                dbSession.commit();
                                log.info("DB Client Afte rCommit");
                            } catch (Exception e) {
                                log.error("Error updating task uuid", e);
                            }
                        }
                    });
        }
    }

    @Override
    public String getDescription() {
        return "Add Codescan jobId MDC variable.";
    }
}
